# Generated by Django 2.2.5 on 2020-04-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200404_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bath',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bed',
            new_name='beds',
        ),
    ]
